server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.50.243:3306/tensquare_recruit?characterEncoding=utf-8
    url: jdbc:mysql://192.168.0.9:3306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
